[project]
name = "app"
version = "1.0.0"
description = "Trivial flask application"
dependencies = [
    "flask~=2.0"
]

[project.optional-dependencies]
test = ["pytest ~=3.0.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
